// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaleProjetoMVC.Models;

namespace SaleProjetoMVC.Migrations
{
    [DbContext(typeof(SaleProjetoMVCContext))]
    [Migration("20190716154351_OtherMigrations")]
    partial class OtherMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SaleProjetoMVC.Models.Departament", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Departament");
                });

            modelBuilder.Entity("SaleProjetoMVC.Models.SalesRecord", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<DateTime>("Date");

                    b.Property<int?>("Sellerid");

                    b.Property<int>("Status");

                    b.HasKey("id");

                    b.HasIndex("Sellerid");

                    b.ToTable("SalesRecord");
                });

            modelBuilder.Entity("SaleProjetoMVC.Models.Seller", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BaseSalary");

                    b.Property<DateTime>("BirthDate");

                    b.Property<int?>("Departamentid");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("id");

                    b.HasIndex("Departamentid");

                    b.ToTable("Seller");
                });

            modelBuilder.Entity("SaleProjetoMVC.Models.SalesRecord", b =>
                {
                    b.HasOne("SaleProjetoMVC.Models.Seller", "Seller")
                        .WithMany("Sales")
                        .HasForeignKey("Sellerid");
                });

            modelBuilder.Entity("SaleProjetoMVC.Models.Seller", b =>
                {
                    b.HasOne("SaleProjetoMVC.Models.Departament", "Departament")
                        .WithMany("Sellers")
                        .HasForeignKey("Departamentid");
                });
#pragma warning restore 612, 618
        }
    }
}
